version: "3"

services:
  app:
    build: .
    volumes:
      - $HOME/.m2:/root/.m2
    depends_on:
      - db

  db:
    image: influxdb:1.7-alpine
    volumes:
      - $HOME/.influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: cabano
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: influxdb
      INFLUXDB_USER_PASSWORD: influxdb

  chronograf:
    image: chronograf:1.7-alpine
    volumes:
      - $HOME/.chronograf:/var/lib/chronograf
    command: --influxdb-url=http://db:8086
    ports:
      - 8888:8888
    depends_on:
      - db
